class SwapPageElements:
    btn_advance_config = "//button[@id ='toggle-expert-mode-button']"
    open_chains = "//div[contains(text(),'Ethereum')]"
    btn_swap = "//*[text()='Swap']"
    btn_advance_setting = "//button[@id='open-settings-dialog-button' and @aria-label ='Transaction Settings']"
    title_advance_setting = "//div[contains(text(),'Advanced Settings')]"
    slippage_text_field = "(//input[contains(@class,'TransactionSettings__Input-vnkaew-2')])[1]"
    btn_more_information = "//div[contains(text(),'MORE INFORMATION')]"
    minimum_received_value = "(//div[contains(@class,'theme__TextWrapper-sc-1hgqg2t-0')])[4]"
    gas_fee_value = "(//div[contains(@class,'theme__TextWrapper-sc-1hgqg2t-0 jScpjN ')])[6]"
    price_impact_value = "(//div[contains(@class,'theme__TextWrapper-sc-1hgqg2t-0 jScpjN ')])[8]"
    amount_in = "#swap-currency-input .token-amount-input"
    amount_out = "#swap-currency-output .token-amount-input"
    currency_input = "#swap-currency-input .token-symbol-container"
    current_output = "#swap-currency-output .token-symbol-container"
    slippage_value = "//div[contains(@class,'styleds__ClickableText-sc-8mz0kz-1')]"
    transaction_time_limit_field = "(//input[contains(@class,'TransactionSettings__Input-vnkaew-2')])[2]"
    advance_mode_on = "(//span[contains(@class,'Toggle__ToggleElement-k4pnr9-1')])[1]"
    advance_mode_off = "(//span[contains(@class,'Toggle__ToggleElement-k4pnr9-1')])[2]"
    advance_mode_term = "//div[contains(@class,'css-stj5vf')]"
    advance_mode_term_1 = "//div[@class='css-1pxm4lx']"
    btn_cancel = "//button[contains(text(),'Cancel')]"
    btn_confirm = "//button[contains(text(),'Confirm')]"
    advance_mode_confirm_text_field = "(//input[contains(@class,'TransactionSettings__StyledInput-vnkaew-9')])"
    max_slippage_waring_mgs = "(//div[contains(@class,'sc-bdVaJa Row-y1019l-0 Row__RowBetween-y1019l-1 bvXRHz')])[3]"
